@startuml

left to right direction
actor 警员
actor 管理员
警员 <|-- 管理员
rectangle 人口管控系统 {
警员 -- (用水异常判断)
警员 -- (调查走访管理)
警员 -- (人口信息查询)
警员 -- (房屋信息查询)
管理员 -- (小区警员维护)
管理员 -- (用户权限管理)

(调查走访管理) .> (用水异常判断) : extends
(调查走访管理) .> (房屋信息查询) : includes

}

@enduml
